# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20171218_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Password',
        ),
    ]
